try:
    print(x)
except NameError:
    print("Ops, a variavel n√£o foi declarada")